# Generated by Django 3.0 on 2020-09-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='day')),
                ('hours', models.FloatField(verbose_name='hours worked')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='finance.Counterparty')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shop', to='finance.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='fire date')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='finance.Counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='day')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payment', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='finance.Counterparty')),
                ('salary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_type', to='finance.Cost')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_shop', to='finance.Shop')),
            ],
        ),
    ]
